# Generated by Django 2.2.5 on 2020-05-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200527_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='goods',
            new_name='spu',
        ),
    ]
